import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        black: "rgb(20 21 32)",
        danger: {
          50: "rgb(253 245 243)",
          100: "rgb(252 232 228)",
          200: "rgb(250 213 206)",
          300: "rgb(243 172 158)",
          400: "rgb(237 143 124)",
          500: "rgb(225 106 82)",
          600: "rgb(205 78 53)",
          700: "rgb(172 63 41)",
          800: "rgb(143 54 37)",
          900: "rgb(119 51 37)",
          950: "rgb(64 23 15)",
        },
        green: {
          50: "rgb(248 251 252)",
          100: "rgb(242 247 248)",
          200: "rgb(225 237 239)",
          300: "rgb(211 229 232)",
          400: "rgb(198 221 226)",
          500: "rgb(183 212 218)",
          600: "rgb(130 181 191)",
          700: "rgb(81 145 158)",
          800: "rgb(54 96 104)",
          900: "rgb(28 50 54)",
        },
        info: {
          200: "rgb(202 218 243)",
          300: "rgb(166 195 234)",
        },
        lila: {
          50: "rgb(251 250 255)",
          100: "rgb(247 245 255)",
          200: "rgb(234 230 254)",
          300: "rgb(226 220 254)",
          400: "rgb(214 206 253)",
          500: "rgb(200 190 253)",
          600: "rgb(180 166 252)",
          700: "rgb(160 141 251)",
          800: "rgb(131 107 250)",
          900: "rgb(85 52 249)",
        },
        red: {
          50: "rgb(254 251 251)",
          100: "rgb(253 247 248)",
          200: "rgb(251 234 237)",
          300: "rgb(248 221 226)",
          400: "rgb(246 208 215)",
          500: "rgb(243 196 205)",
          600: "rgb(238 170 183)",
          700: "rgb(232 141 157)",
          800: "rgb(222 94 117)",
          900: "rgb(191 39 67)",
        },
        success: {
          50: "rgb(243 250 248)",
          100: "rgb(215 240 236)",
          200: "rgb(191 231 225)",
          300: "rgb(126 202 193)",
          400: "rgb(83 174 166)",
          500: "rgb(58 146 141)",
          600: "rgb(44 117 114)",
          700: "rgb(39 94 92)",
          800: "rgb(35 76 76)",
          900: "rgb(32 65 63)",
          950: "rgb(14 36 37)",
        },
        transparent: "transparent",
        violet: {
          300: "rgb(196 181 253)",
        },
        warning: {
          50: "rgb(254 245 238)",
          100: "rgb(252 233 216)",
          200: "rgb(247 206 177)",
          300: "rgb(242 171 126)",
          400: "rgb(236 128 75)",
          500: "rgb(231 95 40)",
          600: "rgb(216 71 30)",
          700: "rgb(180 52 26)",
          800: "rgb(143 43 29)",
          900: "rgb(116 38 26)",
          950: "rgb(62 17 12)",
        },
        white: "rgb(245 245 245)",
        yellow: {
          50: "rgb(255 253 250)",
          100: "rgb(255 250 245)",
          200: "rgb(255 245 235)",
          300: "rgb(254 238 220)",
          400: "rgb(254 233 210)",
          500: "rgb(254 227 198)",
          600: "rgb(253 201 145)",
          700: "rgb(252 164 70)",
          800: "rgb(236 124 4)",
          900: "rgb(170 89 3)",
        },
        "prose-body": "var(--tw-prose-body)",
        "prose-lead": "var(--tw-prose-lead)",
        "prose-links": "var(--tw-prose-links)",
        "prose-bold": "var(--tw-prose-bold)",
        "prose-counters": "var(--tw-prose-counters)",
        "prose-bullets": "var(--tw-prose-bullets)",
        "prose-headings": "var(--tw-prose-headings)",
        "prose-hr": "var(--tw-prose-hr)",
        "prose-quotes": "var(--tw-prose-quotes)",
        "prose-quote-borders": "var(--tw-prose-quote-borders)",
        "prose-pre-code": "var(--tw-prose-pre-code)",
        "prose-pre-bg": "var(--tw-prose-pre-bg)",
        "prose-th-borders": "var(--tw-prose-th-borders)",
        "prose-td-borders": "var(--tw-prose-td-borders)",
        "prose-captions": "var(--tw-prose-captions)",
        "prose-kbd": "var(--tw-prose-kbd)",
        "prose-kbd-shadows": "var(--tw-prose-kbd-shadows)",
        "prose-code": "var(--tw-prose-code)",
      },
      boxShadow: {
        DEFAULT: "0px 5px",
        large: "0px 10px",
        small: "0px 3px",
        tiny: "0px 1.5px",
      },
    },
  },
  plugins: [
    plugin(function ({ addComponents, theme }) {
      addComponents({
        ".prose-styles": {
          color: theme("colors.prose-body"),
          maxWidth: "65ch",
          fontSize: "1.25rem",
          fontWeight: "500",
          lineHeight: "1.8",
          "& :where(p)": {
            marginTop: "1.2em",
            marginBottom: "1.2em",
          },
          "& :where([class~=lead])": {
            color: theme("colors.prose-lead"),
            fontSize: "1.2em",
            lineHeight: "1.5",
            marginTop: "1em",
            marginBottom: "1em",
          },
          "& :where(a)": {
            color: theme("colors.prose-links"),
            textDecoration: "underline",
            fontWeight: "500",
          },
          "& :where(strong)": {
            color: theme("colors.prose-bold"),
            fontWeight: "600",
          },
          "& :where(a strong)": {
            color: "inherit",
          },
          "& :where(blockquote strong)": {
            color: "inherit",
          },
          "& :where(thead th strong)": {
            color: "inherit",
          },
          "& :where(ol)": {
            listStyleType: "decimal",
            marginTop: "1.25em",
            marginBottom: "1.25em",
            paddingInlineStart: "1.625em",
          },
          "& :where(ol[type=A])": {
            listStyleType: "upper-alpha",
          },
          "& :where(ol[type=a])": {
            listStyleType: "lower-alpha",
          },
          "& :where(ol[type=I])": {
            listStyleType: "upper-roman",
          },
          "& :where(ol[type=i])": {
            listStyleType: "lower-roman",
          },
          '& :where(ol[type="1"])': {
            listStyleType: "decimal",
          },
          "& :where(ul)": {
            listStyleType: "disc",
            marginTop: "1.25em",
            marginBottom: "1.25em",
            paddingInlineStart: "1.625em",
          },
          "& :where(ol>li)::marker": {
            fontWeight: "400",
            color: theme("colors.prose-counters"),
          },
          "& :where(ul>li)::marker": {
            color: theme("colors.prose-bullets"),
          },
          "& :where(dt)": {
            color: theme("colors.prose-headings"),
            fontWeight: "600",
            marginTop: "1.25em",
          },
          "& :where(hr)": {
            borderColor: theme("colors.prose-hr"),
            borderTopWidth: "1px",
            marginTop: "3em",
            marginBottom: "3em",
          },
          "& :where(blockquote)": {
            fontWeight: "500",
            fontStyle: "italic",
            color: theme("colors.prose-quotes"),
            borderInlineStartWidth: ".25rem",
            borderInlineStartColor: theme("colors.prose-quote-borders"),
            quotes: '"“""”""‘""’"',
            marginTop: "1.6em",
            marginBottom: "1.6em",
            paddingInlineStart: "1em",
          },
          "& :where(blockquote p:first-of-type)::before": {
            content: "open-quote",
          },
          "& :where(blockquote p:last-of-type)::after": {
            content: "close-quote",
          },
          "& :where(h1)": {
            color: theme("colors.prose-headings"),
            fontWeight: "800",
            fontSize: "2.25em",
            marginTop: "0",
            marginBottom: ".8888889em",
            lineHeight: "1.1111111",
          },
          "& :where(h1 strong)": {
            fontWeight: "900",
            color: "inherit",
          },
          "& :where(h2)": {
            color: theme("colors.prose-headings"),
            fontWeight: "700",
            fontSize: "1.5em",
            marginTop: "2em",
            marginBottom: "1em",
            lineHeight: "1.3333333",
          },
          "& :where(h2 strong)": {
            fontWeight: "800",
            color: "inherit",
          },
          "& :where(h3)": {
            color: theme("colors.prose-headings"),
            fontWeight: "600",
            fontSize: "1.5em",
            marginTop: "1.6em",
            marginBottom: ".6em",
            lineHeight: "1.333333",
          },
          "& :where(h3 strong)": {
            fontWeight: "700",
            color: "inherit",
          },
          "& :where(h4)": {
            color: theme("colors.prose-headings"),
            fontWeight: "600",
            marginTop: "1.5em",
            marginBottom: ".5em",
            lineHeight: "1.5",
          },
          "& :where(h4 strong)": {
            fontWeight: "700",
            color: "inherit",
          },
          "& :where(picture)": {
            display: "block",
            marginTop: "2em",
            marginBottom: "2em",
          },
          "& :where(kbd)": {
            fontWeight: "500",
            fontFamily: "inherit",
            color: theme("colors.prose-kbd"),
            boxShadow:
              "0 0 0 1px rgb(var(--tw-prose-kbd-shadows) / 10%),0 3px rgb(var(--tw-prose-kbd-shadows) / 10%)",
            fontSize: ".875em",
            borderRadius: ".3125rem",
            paddingTop: ".1875em",
            paddingInlineEnd: ".375em",
            paddingBottom: ".1875em",
            paddingInlineStart: ".375em",
          },
          "& :where(code)": {
            color: theme("colors.prose-code"),
            fontWeight: "600",
            fontSize: ".875em",
          },
          "& :where(code)::before": {
            content: '"`"',
          },
          "& :where(code)::after": {
            content: '"`"',
          },
          "& :where(a code)": {
            color: "inherit",
          },
          "& :where(h1 code)": {
            color: "inherit",
          },
          "& :where(h2 code)": {
            color: "inherit",
            fontSize: ".875em",
          },
          "& :where(h3 code)": {
            color: "inherit",
            fontSize: ".9em",
          },
          "& :where(h4 code)": {
            color: "inherit",
          },
          "& :where(blockquote code)": {
            color: "inherit",
          },
          "& :where(thead th code)": {
            color: "inherit",
          },
          "& :where(pre)": {
            color: theme("colors.prose-pre-code"),
            backgroundColor: theme("colors.prose-pre-bg"),
            overflowX: "auto",
            fontWeight: "400",
            fontSize: ".875em",
            lineHeight: "1.7142857",
            borderRadius: theme("borderRadius.md"),
            marginTop: "2em",
            marginBottom: "2em",
            paddingTop: "1em",
            paddingInlineEnd: "1.5em",
            paddingBottom: "1em",
            paddingInlineStart: "1.5em",
          },
          "& :where(pre code)": {
            backgroundColor: "transparent",
            borderWidth: "0",
            borderRadius: "0",
            padding: "0",
            fontWeight: "inherit",
            color: "inherit",
            fontSize: "inherit",
            fontFamily: "inherit",
            lineHeight: "inherit",
          },
          "& :where(pre code)::before": {
            content: "none",
          },
          "& :where(pre code)::after": {
            content: "none",
          },
          "& :where(table)": {
            width: "100%",
            tableLayout: "auto",
            textAlign: "start",
            marginTop: "2em",
            marginBottom: "2em",
            fontSize: ".875em",
            lineHeight: "1.7142857",
          },
          "& :where(thead)": {
            borderBottomWidth: "1px",
            borderBottomColor: theme("colors.prose-th-borders"),
          },
          "& :where(thead th)": {
            color: theme("colors.prose-headings"),
            fontWeight: "600",
            verticalAlign: "bottom",
            paddingInlineStart: "0",
            paddingInlineEnd: "0",
            paddingTop: "0",
            paddingBottom: ".5em",
          },
          "& :where(tbody tr)": {
            borderBottomWidth: "1px",
            borderBottomColor: theme("colors.prose-td-borders"),
          },
          "& :where(tbody tr:last-child)": {
            borderBottomWidth: "0",
          },
          "& :where(tbody td)": {
            verticalAlign: "baseline",
            paddingTop: ".5em",
            paddingBottom: ".5em",
            paddingInlineStart: "0",
            paddingInlineEnd: "0",
          },
          "& :where(tfoot td)": {
            verticalAlign: "top",
          },
          "& :where(figcaption)": {
            color: theme("colors.prose-captions"),
            fontSize: ".875em",
            lineHeight: "1.4285714",
            marginTop: ".8571429em",
          },
          "& :where(h2 + *)": {
            marginTop: "0",
          },
          "& :where(h3 + *)": {
            marginTop: "0",
          },
          "& :where(h4 + *)": {
            marginTop: "0",
          },
        },
      });
    }),
  ],
};
export default config;
