import type { Metadata, Viewport } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/next";
import { PROD_URL } from "@/lib/constants";

const bricolage_grotesque = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s - Friend, the more the merrier!",
    default: "Friend Blitz - Friend, the more the merrier!", // a default is required when creating a template
  },
  description: "Generated by create next app",
  metadataBase: new URL(PROD_URL), // a default is required when using alternates
  alternates: {
    canonical: "/",
    languages: {
      "en-US": "/en-US",
    },
  },
  openGraph: {
    title: "Friend Blitz",
    description: "Generated by create next app",
    url: "/",
    siteName: "Friend Blitz",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Friend Blitz",
    description: "Generated by create next app",
    creator: "@friendblitz",
  },
};

export const viewport: Viewport = {
  themeColor: "#f5f5f5",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth selection:bg-black selection:text-lila-500"
      suppressHydrationWarning
    >
      <body
        className={cn(
          bricolage_grotesque.className,
          "border-x-2 border-black bg-white flex flex-col min-h-screen"
        )}
      >
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            className: `${bricolage_grotesque.className} text-lg`,
          }}
        />
        <Analytics />
      </body>
    </html>
  );
}
